### ISSUE TITLE
Add sensor_msgs/Image adapter to cv::Mat

### ISSUE THREAD

**Issue by roncapat** [roncapat/ros2_native_adapters#1]
This should follow the other two adapters structure (so, for now, no lazy conversion as the cv::Mat adapter found in ROS 2 vision stack).

Lazy conversion of every adapter may be evaluated in future work.

**Comment by roncapat** [comment]
Closed by #2

**Comment by ZhenshengLee** [comment]
> Lazy conversion of every adapter may be evaluated in future work.

- What does this lazy conversion of adapter mean?
- Does this feature already merged in?

**Comment by roncapat** [comment]
[Example of lazy conversion](https://github.com/clalancette/type_adapt_example/blob/main/include/type_adapt_example/cv_mat_sensor_msgs_image_type_adapter.hpp)

>  The two main use cases for this are publishing user controlled data, and
>  recieving data from the middleware that may have been a ROS message
>  originally or may have been an cv::Mat originally.
>  
>  In the first case, publishing user owned data, the user will want to provide
>  their own cv::Mat.
>  The cv::Mat may own the data or it may not, so in the latter case, it is up
>  to the user to ensure the data the cv::Mat points to remains valid as long
>  as the middleware needs it.
>  
>  In the second case, receiving data from the middleware, the middleware will
>  either give a new ROSCvMatContainer which owns a sensor_msgs::msg::Image or
>  it will give a ROSCvMatContainer that was previously published by the user
>  (in the case of intra-process communication).
>  If the container owns the sensor_msgs::msg::Image, then the cv::Mat will just
>  reference data field of this message, so the container needs to be kept.
>  If the container was published by the user it may or may not own the data
>  and the cv::Mat it contains may or may not own the data.

**Comment by roncapat** [comment]
@ZhenshengLee no I haven't implemented such type of complexity in these adapters, I prefer to work with native types always inside my ROS 2 nodes.
